scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['192.168.0.105:8083', '192.168.0.105:8081', '192.168.0.105:8082','192.168.0.105:8085']
        labels:
          application: 'BMW Application'