scrape_configs:
  - job_name: 'Spring Boot Application input'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: ['localhost:8083', 'localhost:8081', 'localhost:8082','localhost:8085']
        labels:
          application: 'BMW Application'