server:
  port: 8083
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
        - id: appointment
          uri: lb://APPOINTMENT
          predicates:
            - Path=/api/v1/appointments/**
        - id: flat
          uri: lb://FLAT
          predicates:
            - Path=/api/v1/flats/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka