server:
  port: 8083
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
        - id: appointment
          uri: lb://APPOINTMENT
          predicates:
            - Path=/api/v1/appointments/**
        - id: flat
          uri: lb://FLAT
          predicates:
            - Path=/api/v1/flats/**
        - id: message
          uri: lb://MESSAGE
          predicates:
            - Path=/api/v1/messages/**
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8890/realms/bmw-app
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: [ "health", "prometheus", "info" ]
    endpoint:
      health:
        show-details: always
      metrics:
        enabled: true
      prometheus:
        enabled: true