server:
  port: 8761
spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
management:
  metrics:
    export:
      influx:
        uri: http://localhost:8090
        db: bmw_app_influxdb
        user-name: influxdb
        password: influxpass