server:
  port: 8761
spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
management:
  metrics:
    export:
      influx:
        bucket: bmw-app
        org: bmw-app
        token: Q0w1gIo-fsHECIfUe_hRe-jzGUYoU8qzi5FiGuc1Oc2QobnKLnU81_19MjDTKv7aM10TFQfDWyLTJhfXFq8Qeg==
        uri: http://localhost:8090
        user-name: influxdb
        password: influxpass